# Site settings
title: goSwoosh
email: founders@goswoosh.com
description: > # this means to ignore newlines until "baseurl:"
 We are a high-trust, easy-to-schedule ride service for mountain sports families. 
 Our initial focus is to provide personalized, scheduled and on-demand ride transport for families on the tahoe/truckee ski teams. 
 Our mission is to reduce traffic and environmental impact and help active families with busy schedules.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goswoosh.com" # the base hostname & protocol for your site
twitter_username: rideswoosh

# Build settings
markdown: kramdown
